### ISSUE TITLE
Lack of upper bounds leads to compilation errors

### ISSUE THREAD

**Issue by tdammers** [dterei/memcache-hs#12]
Depending on `memcache` in a cabal project right now causes it to pull in version 3.1.x of the `network` dependency; however, this version is not API-compatible with the 2.x range, and fails to build. Explicitly adding `network <3.0` as a constraint, I can work around the problem, but it would be nice to have proper upper bounds on the dependencies of `memcache` itself.

**Comment by dterei** [comment]
bounds updated recently, see 0.3.0.0 release
