### ISSUE TITLE
Adding to Stackage

### ISSUE THREAD

**Issue by pbrisbin** [dterei/memcache-hs#14]
:wave: Hi there-

Thank you for this client library, it's the one that best met our needs here at Freckle. Would you be willing to add it in Stackage so we can stop carrying it as an `extra-dep`? If not, we might bring it in under our section.

Thanks!

**Comment by dterei** [comment]
Hey @pbrisbin -- Sorry, somehow missed this till now. Is it still useful to do this?

**Comment by pbrisbin** [comment]
Hey, no worries. Yes, being in Stackage is still (and will always be) useful :)

**Comment by pbrisbin** [comment]
Thank you!
