### ISSUE TITLE
`NotEnoughBytes` with payloads bigger than 1420 bytes

### ISSUE THREAD

**Issue by adinapoli** [dterei/memcache-hs#6]
GHC Version: 7.10.2
Platform: Mac OS X El Capitan 10.11.3

Hey @dterei !

First of all thank you for this library, it's one of the best out there when it comes to memcached (kudos for implementing authentication, it's the first thing other projects miss!). At work, I have been trying to use this library to talk to memcachier to provide us with a simple key/value cache, but I'm hitting a strange behaviour I will do my best in trying to explain here.

I have some run-of-the-mill code to provide a cache interface, which is not important, but that I'm reporting here for completeness:

``` haskell
memcacheLookup :: (IsKey k, IsValue v) => RemoteCacheProvider Memcache -> k -> IO (Maybe v)
memcacheLookup (MemcacheProvider client) k = do
  res <- Memcache.get client (toS $ toKey k)
  case res of
    Nothing -> return Nothing
    Just (val, _, _) -> return . JSON.decode . toS $ val

memcacheStore :: (IsKey k, IsValue v) => RemoteCacheProvider Memcache -> k -> v -> IO ()
memcacheStore (MemcacheProvider client) k v = do
  let key     = toS $ toKey k
  let payload = toS . JSON.encode $ v
  res <- Memcache.get client key
  case res of
    Nothing -> void $ Memcache.set client key payload 0 0
    Just (_, _, cas) -> void $ Memcache.set' client key payload 0 0 cas

memcacheDelete :: (IsKey k, IsValue v) => RemoteCacheProvider Memcache -> k -> IO (Proxy v)
memcacheDelete (MemcacheProvider client) k = do
  void $ Memcache.delete client (toS $ toKey k) 0
  return Proxy
```

As you can see, we are serialising/deserialising back and forth some JSON, but this is irrelevant. I have then written a spec which triggers a surprising problem:

``` haskell
newtype TestPayload = TP { value :: T.Text } deriving (Show, Eq)

deriveJSON defaultOptions ''TestPayload

memcacheCacheSpecs :: AppEnv -> Spec
memcacheCacheSpecs e = beforeAll wipeCache $ do
  let cache = e ^. appCache
  describe "Memcache Cache & Caching" $ do
    it "Storing and looking up stuff yield (Just x)" $ do
      let v = TP (T.replicate 2123 "a")
      putStrLn $ "====> SIZE: " <> show (B.length $ toS (JSON.encode v))
      cacheStore cache (CK $ UserID 50) v
      (r :: Maybe TestPayload) <- cacheLookup cache (CK $ UserID 50)
      r `shouldBe` Just v
  where
    wipeCache = do
      (_ :: Proxy TestPayload) <- cacheDelete (e ^. appCache) (CK $ UserID 50)
      return ()
```

As you can see, I'm simplifying everything at maximum, which is essentially sending over the wire a simple json filled with all `a` s, something like:

```
{ "value": "aaaaaaaaaaa" }
```

The error being thrown by your library, if I try to `cacheLookup` this value after a `cacheStore`, is `NotEnoughBytes`. I have dug deeper into the internals and indeed such error is thrown here, when the library receives less than the expected amount of bytes from the socket:

https://github.com/dterei/memcache-hs/blob/master/Database/Memcache/Wire.hs#L44

I have forked the library and added a bunch of `putStrLn` statements, like this:

``` haskell
recv :: Socket -> IO Response
recv s = do
    header <- recvAll mEMCACHE_HEADER_SIZE
    let h = dzHeader' (L.fromChunks [header])
    if bodyLen h > 0
        then do
          putStrLn $ "==> BodyLen: " <> show (bodyLen h)
          let bytesToRead = fromIntegral $ bodyLen h
          putStrLn $ "==> BytesToRead: " <> show bytesToRead
          body <- recvAll bytesToRead
          return $ dzBody' h (L.fromChunks [body])
        else return $ dzBody' h L.empty
  where
    recvAll :: Int -> IO B.ByteString
    recvAll n = do
        putStrLn $ "==> Going to read " <> show n <> " bytes..."
        buf <- N.recv s n
        let bufLen = B.length buf
        putStrLn $ "==> I have read " <> show bufLen <> " bytes..."
        if bufLen == n
          then return buf
          else throwIO NotEnoughBytes
``` 

And, armed with this tools, I have rerun the specs:

![screen shot 2016-02-25 at 12 51 47](https://cloud.githubusercontent.com/assets/442035/13319084/6fe5de6c-dbbf-11e5-866a-98f3c4b43289.png)

As you can see, there is this magical `1424` bytes value which is the maximum value we get back from the socket. If I try to pass a smaller payload, which size is smaller or equal than 1424, it works correctly. I have found this empirical number which is **1420**: if my payload is bigger than 1420 bytes, the library will try to read more than `1424` bytes (Apparently there are 4 extra bytes at the end coming out of nowhere -- padding perhaps?) and everything breaks.

I have tried to perform a get on large payload with a Python client, to try to rule out as many problems as possible, and the latter works correctly:

![screen shot 2016-02-25 at 12 31 39](https://cloud.githubusercontent.com/assets/442035/13319139/dc9cb026-dbbf-11e5-900f-c1ea4935f15d.png)

It's also using the same memcachier instance, which rules out some weird memcachier config issue.

I think that, from my perspective, we are faced with one of these three:

1. There is a bug in my understanding of this API and/or in my `store/lookup/delete` functions

2. There is a bug in this library

3. There is a very sneaky bug in the `network` package, specifically in the `recv` function for `ByteString`s.

What do you think? Any input from you would be highly appreciated and value? Please shout if you need any reproduction steps. 

Thanks a ton!

Alfredo

**Comment by dterei** [comment]
Alfredo,

Thanks for the kind words! Really happy you are using the library and (somewhat) finding it useful.

There's a lot of info to the bug report, which is helpful. However, am I correct is summarising this to:

"Performing a `GET` on a key-value pair where the value length is more than 1420 bytes causes a `NotEnoughBytes` error"

?

The first thing that comes to mind is that 1420 is very much around the typical MTU value of IP/ethernet. So perhaps there is a bug in how either the memcache library or the network library handles fragmented packets. Very likely the memcache package.

**Comment by adinapoli** [comment]
Hey @dterei ,

thanks for the quick reply!

> "Performing a GET on a key-value pair where the value length is more than 1420 bytes causes a NotEnoughBytes error"

Yes, I think this sentence nicely summarise what I have been experiencing.

> The first thing that comes to mind is that 1420 is very much around the typical MTU value of IP/ethernet. So perhaps there is a bug in how either the memcache library or the network library handles fragmented packets.

Yes, that's a very good intuition here. I would expect that memcached won't even bother trying to send big payloads over the wire, and I'm staring to think it's client responsibility to read everything on its end. After all, that's why they are sending the body length in the `mEMCACHED_HEADER`, right? I think one possible fix might be to extend [recvAll](https://github.com/dterei/memcache-hs/blob/master/Database/Memcache/Wire.hs#L40) to work as follows:

- If you receive exactly `n` bytes, where `n == bodyLen`, then return (like before)
- If you receive less than `bodyLen` bytes, recur expecting to read more or exactly `bodyLen - n`

I guess the question would be: How could be determine if we are receiving less bytes due to an error (example, the connection dropped) or because the payload is fragmented? One approach that might work could be use [sockets predicates](http://hackage.haskell.org/package/network-2.6.2.1/docs/Network-Socket.html#v:isConnected) to assess whether the socket is still listening; if it is, we recur, otherwise, we throw a `NotEnoughBytes`, as before.

Am I making sense? Bear in mind I still didn't have my morning :coffee:  :wink: 

I can try to cook up something in a PR, if you want.
